export const ROLES = {
  PATIENT: 'PATIENT',
  DOCTOR: 'DOCTOR',
  ADMIN:'ADMIN',
  PROVIDER_ADMIN: 'PROVIDER_ADMIN',
  RECEPTIONIST: 'RECEPTIONIST'
};

export const PROVIDER = {
  DAB : 'DAB'
};

export const COMMISSION_MODES = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED: 'FIXED',
};

export const TAX_MODES = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED: 'FIXED',
};

export const TAX_VALUES = {
  ZERO_PERCENTAGE: 0,
  FIVE_PERCENTAGE: 5,
  TWELVE_PERCENTAGE: 12,
  EIGHTEEN_PERCENTAGE: 18,
  TWENTY_EIGHT_PERCENTAGE: 28,
};


export const PROVIDER_TYPES = {
  HOSPITAL : 'HOSPITAL',
  CLINIC: 'CLINIC'
}

export const PROVIDER_UNIQUE_CODE = {
  HOSPITAL : 'HSPTL',
  CLINIC: 'CLNC'
}

export const SERVICES_OFFERED = {
  IN_PATIENT : 'IN_PATIENT',
  OUT_PATIENT : 'OUT_PATIENT',
  BOTH : 'BOTH'
}

export const SERVICE = {
  ONLINE:'ONLINE',
  OFFLINE:'OFFLINE'
}

export const CURRENCY = {
  INDIA: 'INR',
};


export const OWNERSHIP = {
  INDIVIDUAL : 'INDIVIDUAL',
  PARTNERSHIP : 'PARTNERSHIP',
  CORPORATE : 'CORPORATE'
}

export const SUBSCRIPTIONS_VALIDITY = {
  MONTHLY: 'MONTHLY',
  BI_YEARLY: 'BI_YEARLY',
  YEARLY: 'YEARLY',
};

export const PAYMENT_STATUSES = {
  PAID: 'PAID',
  PENDING: 'PENDING',
};

export const SUBSCRIPTIONS = {
  BASIC: 'BASIC',
  BASIC_PLUS: 'BASIC_PLUS',
  PREMIUM: 'PREMIUM',
  DELUXE: 'DELUXE',
};

export const DOCTOR_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

export const DOCTORS_CATEGORIES = {
  GENERAL_SUGEONS :'GENERAL_SUGEONS',
  UROLOGIST :'UROLOGIST',
  SPORTS_MEDICINE_SPECIALIST :'SPORTS_MEDICINE_SPECIALIST',
  SLEEP_MEDICINE_SPECIALIST:'SLEEP_MEDICINE_SPECIALIST',
  RHEUMATOLOGIST:'RHEUMATOLOGIST',
  RADIOLOGIST:'RADIOLOGIST',
  PULMONOLOGIST:'PULMONOLOGIST',
  PSYCHIATRIST:'PSYCHIATRIST',
  PLASTICSURGEON:'PLASTICSURGEON',
  PHYSIATRIST:'PHYSIATRIST',
  PEDIATRICIAN:'PEDIATRICIAN',
  PATHOLOGIST:'PATHOLOGIST',
  OTOLARYNGOLOGIST:'OTOLARYNGOLOGIST',
  OPHTHALMOLOGIST:'OPHTHALMOLOGIST',
  ONCOLOGIST:'ONCOLOGIST',
  NEPHROLOGISTS:'NEPHROLOGISTS',
  NEUROLOGISTS:'NEUROLOGISTS',
  ORTHOPAEDIST:'ORTHOPAEDIST',
  GASTROENTEROLOGIST:'GASTROENTEROLOGIST',
  ORTHOPEDICS:'ORTHOPEDICS',
  INTERNAL_MEDICINE:'INTERNAL_MEDICINE',
  GERIARICS:'GERIARICS',
  CARDIOLOGIST:'CARDIOLOGIST',
  DERMATOLOGIST:'DERMATOLOGIST',
  ENDOCRINOLOGIST:'ENDOCRINOLOGIST',
}
