export const ROLES = {
  PATIENT: 'PATIENT',
  DOCTOR: 'DOCTOR',
  ADMIN:'ADMIN',
  PROVIDER: 'PROVIDER'
};

export const PROVIDER = {
  DAB : 'DAB'
};

export const COMMISSION_MODES = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED: 'FIXED',
};

export const PROVIDER_TYPES = {
  HOSPITAL : 'HOSPITAL',
  CLINIC: 'CLINIC'
}

export const PROVIDER_UNIQUE_CODE = {
  HOSPITAL : 'HSPTL',
  CLINIC: 'CLNC'
}

export const SERVICES_OFFERED = {
  IN_PATIENT : 'IN_PATIENT',
  OUT_PATIENT : 'OUT_PATIENT',
  BOTH : 'BOTH'
}

export const OWNERSHIP = {
  INDIVIDUAL : 'INDIVIDUAL',
  PARTNERSHIP : 'PARTNERSHIP',
  CORPORATE : 'CORPORATE'
}

export const SUBSCRIPTIONS_VALIDITY = {
  MONTHLY: 'MONTHLY',
  BI_YEARLY: 'BI_YEARLY',
  YEARLY: 'YEARLY',
};

export const PAYMENT_STATUSES = {
  PAID: 'PAID',
  PENDING: 'PENDING',
};

export const SUBSCRIPTIONS = {
  BASIC: 'BASIC',
  BASIC_PLUS: 'BASIC_PLUS',
  PREMIUM: 'PREMIUM',
  DELUXE: 'DELUXE',
};
